const initialState = {
  loading: false,
  projects: [],
  photos: [],
  builds: [],
  buildFiltersActive: { Built: true },
  keysets: [],
  keysetSort: 'purchase_date',
  keysetDesc: true,
  switches: [],
  switchesSort: 'purchase_date',
  switchesDesc: true,
  collectionUpdated: '',
  links: [],
  plates: [],
  gear: [],
  gearDescriptions: [],
  commands: [],
  social: {
    instagram: 'https://www.instagram.com/cgbuen/',
    email: 'chris@cgbuen.io',
    linkedin: 'https://www.linkedin.com/in/christopherbuenaventura/',
    twitch: 'https://www.twitch.tv/cgbuen',
    twitter: 'https://twitter.com/cgbuen',
    github: 'https://github.com/cgbuen',
    youtubeM: 'https://www.youtube.com/@cornerblockers',
    youtubeV: 'https://www.youtube.com/@cgbuenVODs',
    discordP: 'cgbuen',
    discordS: 'https://discord.gg/EayZKHK',
    sffb: 'https://us-p2p.netdonor.net/1803/general/61375/cgbuen',
  },
}

export default initialState
